### ISSUE TITLE
Encountered an issue in Attention part of odconv.py

### ISSUE THREAD

**Issue by massarfusion** [OSVAI/ODConv#23]
When I try to apply ODConv to yolov7 , the following prompt was shown:

`File "D:\YOLOv7-ODConv\models\ODConv.py", line 81, in forward
    x = self.bn(x)
  File "D:\Anaconda\envs\yolov7\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconda\envs\yolov7\lib\site-packages\torch\nn\modules\batchnorm.py", line 182, in forward
    self.eps,
  File "D:\Anaconda\envs\yolov7\lib\site-packages\torch\nn\functional.py", line 2448, in batch_norm
    _verify_batch_size(input.size())
  File "D:\Anaconda\envs\yolov7\lib\site-packages\torch\nn\functional.py", line 2416, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 16, 1, 1])`

I am relative new to this field, I will be glad to elaborate but I have no idea what else to report

**Comment by chaoli-ai** [comment]
This issue is caused by the batch normalization used in our ODConv. When using batch normalization, the batch size should at least be 2 during training. You can try to increase the batch size, or replace the batch normalization with layer normalization if you train the model from scratch, or add code as below to freeze the batch normalization layers if you use the pre-trained model.
https://github.com/OSVAI/ODConv/blob/c63c08b170c8a139ee8f31adebfe682829a30200/object_detection/mmdet/models/backbones/od_resnet.py#L161-L164

**Comment by yangdi-cv** [comment]
> 

Hi, I'd like to ask if the issue has been solved?

**Comment by massarfusion** [comment]
> > 
> 
> Hi, I'd like to ask if the issue has been solved?

That one was actually solved by another attempt, in my case, yolov7 will try to check out the output size by feeding a batch=1 
random tensor into the backbone to see whether everything is OK, causing BN error, I just located that line of code and set that random tensor batch=2, since that is meant to be executed once. You might want to follow the instruction or try poking around to do some checking
