### ISSUE TITLE
about bias

### ISSUE THREAD

**Issue by playaswd** [OSVAI/ODConv#25]
Bias is set to none in your code. Is this the same setting for the experiment in the paper? I couldn't find the corresponding description in the paper. If so, could you tell me the reason briefly? Thanks!
https://github.com/OSVAI/ODConv/blob/c63c08b170c8a139ee8f31adebfe682829a30200/modules/odconv.py#L126

**Comment by chaoli-ai** [comment]
Yes, we use same setting for the experiment in our paper. We mainly follow the default setting of torchvision.models.resnet and torchvision.models.mobilenetv2, since each of the convolutional layers in ResNet/MobileNetV2 are mostly followed by a batch normalization layer. For other networks, you may set the bias conditionally. While you can also use aggregation for biases following DyConv, I think maybe it can improve the performance slightly.
