### ISSUE TITLE
About update_temperature!

### ISSUE THREAD

**Issue by Sean-asc** [OSVAI/ODConv#4]
I see you did not finish the function of "update_temperature" in this code version, right?
Updating T from 30 to 1, which is 30 27 24 ...3 1 1 1 ... 1.
But I see your code "class Attention" in a fixed "self.temperature = 1.0".

**Comment by Sean-asc** [comment]
![image](https://user-images.githubusercontent.com/60772811/191440716-c3c31f12-7dbe-4b29-83c6-177cfe707339.png)
And why this kind of combination？ In this situation can get the best result?
but I see your paper:
![image](https://user-images.githubusercontent.com/60772811/191441201-ebecb023-4fb4-41df-aba1-8556e822c826.png)
Confused! Does use sigmoid in all situation can get the best result？

**Comment by chaoli-ai** [comment]
For the first question:
The function "update_temperature" in modules/odconv.py is only a part of temperature annealing, since the temperature is calculated using the information about epoch and iteration.
Please refer to 
https://github.com/OSVAI/ODConv/blob/7fb9a9b0109758b308dafbcf6bb6e6d28c006666/models/od_resnet.py#L113-L116 and
https://github.com/OSVAI/ODConv/blob/7fb9a9b0109758b308dafbcf6bb6e6d28c006666/main.py#L277-L282


For the second question:
The experiments are only about the choice of activation function for spatial dimension. Since the activation function choices for the channel dimension and the convolutional kernel dimension have been thoroughly discussed in the papers of [SE](https://arxiv.org/abs/1709.01507v4) and [DyConv](https://arxiv.org/abs/1912.03458) respectively, we adopt their suggestions for three related attentions defined in our ODConv.

**Comment by Sean-asc** [comment]
I will rewrite the way that DyConv updating T.
And thank you so much for your thoughtfully reply and responding me so fast!
